version: "3.8"

services:
  # =============================================
  # Next.js Frontend
  # =============================================
  dian-frontend:
    build:
      context: ./dian-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://64.23.180.56:8000"
    container_name: dian-frontend
    restart: unless-stopped
    ports:
      - "4000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://64.23.180.56:8000"
    networks:
      - dian-network

networks:
  dian-network:
    driver: bridge
